// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
        /*throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );*/
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALIToGfWFR_hRHnnmnhQXk3biQWCcbsC8',
    appId: '1:132383327423:web:47eaa6fb4d37d7e37a320a',
    messagingSenderId: '132383327423',
    projectId: 'androidmobiletranslatejava22hj',
    authDomain: 'androidmobiletranslatejava22hj.firebaseapp.com',
    storageBucket: 'androidmobiletranslatejava22hj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa7pjFAZfjcg6EXh36pDHWDwH9uXJ51rs',
    appId: '1:132383327423:android:e446b08a998cdab57a320a',
    messagingSenderId: '132383327423',
    projectId: 'androidmobiletranslatejava22hj',
    storageBucket: 'androidmobiletranslatejava22hj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRTlhvahL6L4KDNiNa0B5gk_NzEi5ooDo',
    appId: '1:132383327423:ios:370546603cc360b47a320a',
    messagingSenderId: '132383327423',
    projectId: 'androidmobiletranslatejava22hj',
    storageBucket: 'androidmobiletranslatejava22hj.appspot.com',
    iosBundleId: 'com.example.translate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRTlhvahL6L4KDNiNa0B5gk_NzEi5ooDo',
    appId: '1:132383327423:ios:370546603cc360b47a320a',
    messagingSenderId: '132383327423',
    projectId: 'androidmobiletranslatejava22hj',
    storageBucket: 'androidmobiletranslatejava22hj.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRTlhvahL6L4KDNiNa0B5gk_NzEi5ooDo',
    appId: '1:132383327423:ios:999bd0b934e738727a320a',
    messagingSenderId: '132383327423',
    projectId: 'androidmobiletranslatejava22hj',
    storageBucket: 'androidmobiletranslatejava22hj.appspot.com',
    iosBundleId: 'com.example.translate.RunnerTests',
  );
}
